version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-notes
    ports:
      - 5432:5432
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo-notes
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:r
      - ./db-data/mongo/:/data/db
    command: [--auth]

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todo-notes?schema=public
      - MONGODB_URL=mongodb://admin:password@mongodb:27018/todo-notes?retryWrites=true&w=majority
    volumes:
      - /usr/src/app/node_modules
